### ISSUE TITLE
Server occasionally crashing when player leaves

### ISSUE THREAD

**Issue by onebeastchris** [Oth3r/DirectionHUD-F#7] opened 2023-06-18 12:04 UTC
Hey there! Love the mod, hate the error - "Cannot invoke "java.util.Map.get(Object)" because the return value of "one.oth3r.directionhud.common.files.PlayerData$get.fromMap(one.oth3r.directionhud.utils.Player)" is null".
Seems lime you need a null check to catch that case, as it otherwise crashes the server:
https://mclo.gs/wQPT0Ty

**Comment by Oth3r** [comment] 2023-06-18 13:08
Thanks for the report!
You got any other logs (like for the player disconnecting and it crashing i don't need everything)? I cant seem to reproduce the issue, although it seems that the server thinks that the player disconnected and is still online at the same time...

**Comment by onebeastchris** [comment] 2023-06-18 14:01
The only thing that is shown in the logs is a normal disconnection. No errors or similar, no kicking, no nothing - It usually occurs when there are 5-6 players online.
It hasn't been the first crash on my server, so I had to temporarily remove the mod for now :/

**Comment by Oth3r** [comment] 2023-06-18 14:05
Ah okay, I'll try to get a fix out in the morning, maybe you can see if that does it. It's weird because I can't replicate the issue at all. 
Sorry about the weird bug, hopefully everything else is running smooth for you!

**Comment by Oth3r** [comment] 2023-06-19 06:55
hopefully fixed in [v1.3.6+1.20+1.20.1](https://github.com/Oth3r/DirectionHUD-Fabric/releases/tag/v1.3.6%2B1.20-1.20.1)

**Closed as completed by Oth3r** 2023-06-19 06:55 UTC
Labels: bug
